spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.0.122:8848/

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
